[package]
name = "scanni"
version = "0.1.0"
edition = "2021"
authors = ["Jacob Latonis"]

[build]
target = "x86_64-pc-windows-gnu"

[dependencies]
windows = {version = "0.54.0", features = ["Win32_System_Antimalware",]}
