[package]
name = "scanni"
version = "0.1.0"
edition = "2021"
authors = ["Jacob Latonis"]


[dependencies]
windows = {version = "0.54.0", features = ["Win32_System_Antimalware", "Win32_System_Diagnostics_Etw", "Win32_System_Time"]}